

import { GameSaveData, UnitType } from '../types';
import { INITIAL_LARVA_CAP } from './core';

export const INITIAL_GAME_STATE: GameSaveData = {
    resources: {
        biomass: 15,
        enzymes: 0,
        larva: INITIAL_LARVA_CAP,
        dna: 0,
        mutagen: 0
    },
    hive: {
        unlockedUnits: {
            [UnitType.MELEE]: { id: UnitType.MELEE, level: 1, loadout: [null, null, null, null, null], cap: 200, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.RANGED]: { id: UnitType.RANGED, level: 1, loadout: [null, null, null, null, null], cap: 50, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.PYROVORE]: { id: UnitType.PYROVORE, level: 1, loadout: [null, null, null], cap: 30, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.CRYOLISK]: { id: UnitType.CRYOLISK, level: 1, loadout: [null, null, null], cap: 30, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.OMEGALIS]: { id: UnitType.OMEGALIS, level: 1, loadout: [null, null, null, null], cap: 10, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.QUEEN]: { id: UnitType.QUEEN, level: 1, loadout: [null, null, null], cap: 5, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            
            // Tier 1
            [UnitType.ZERGLING_RAPTOR]: { id: UnitType.ZERGLING_RAPTOR, level: 1, loadout: [null, null], cap: 60, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.EMBER_MITE]: { id: UnitType.EMBER_MITE, level: 1, loadout: [null], cap: 60, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.SPARK_FLY]: { id: UnitType.SPARK_FLY, level: 1, loadout: [null, null], cap: 40, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.FROST_WEEVIL]: { id: UnitType.FROST_WEEVIL, level: 1, loadout: [null, null], cap: 40, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.ACID_MAGGOT]: { id: UnitType.ACID_MAGGOT, level: 1, loadout: [null], cap: 50, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.BONE_BLADE]: { id: UnitType.BONE_BLADE, level: 1, loadout: [null], cap: 60, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.ACID_SPITTER]: { id: UnitType.ACID_SPITTER, level: 1, loadout: [null], cap: 50, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.STATIC_ORB]: { id: UnitType.STATIC_ORB, level: 1, loadout: [null], cap: 40, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.CINDER_LING]: { id: UnitType.CINDER_LING, level: 1, loadout: [null], cap: 60, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.FROST_SHARD]: { id: UnitType.FROST_SHARD, level: 1, loadout: [null], cap: 40, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            // Tier 2
            [UnitType.LIGHTNING_SKINK]: { id: UnitType.LIGHTNING_SKINK, level: 1, loadout: [null, null, null], cap: 20, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.SPINE_HURLER]: { id: UnitType.SPINE_HURLER, level: 1, loadout: [null, null], cap: 25, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.MAGMA_GOLEM]: { id: UnitType.MAGMA_GOLEM, level: 1, loadout: [null, null, null], cap: 10, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.PLAGUE_BEARER]: { id: UnitType.PLAGUE_BEARER, level: 1, loadout: [null, null], cap: 15, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.SIEGE_BEETLE]: { id: UnitType.SIEGE_BEETLE, level: 1, loadout: [null, null], cap: 15, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.FROST_WARD]: { id: UnitType.FROST_WARD, level: 1, loadout: [null, null], cap: 10, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.MAGMA_SPRAYER]: { id: UnitType.MAGMA_SPRAYER, level: 1, loadout: [null, null], cap: 20, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.SHOCK_ROACH]: { id: UnitType.SHOCK_ROACH, level: 1, loadout: [null, null], cap: 20, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.VILE_CRAWLER]: { id: UnitType.VILE_CRAWLER, level: 1, loadout: [null, null], cap: 15, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            // Tier 3
            [UnitType.WINTER_WITCH]: { id: UnitType.WINTER_WITCH, level: 1, loadout: [null, null, null], cap: 8, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.PULSE_BEAST]: { id: UnitType.PULSE_BEAST, level: 1, loadout: [null, null, null], cap: 8, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.CORRUPTOR]: { id: UnitType.CORRUPTOR, level: 1, loadout: [null, null, null], cap: 8, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.PHANTOM_ASSASSIN]: { id: UnitType.PHANTOM_ASSASSIN, level: 1, loadout: [null, null, null], cap: 8, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.INFERNO_JUDGE]: { id: UnitType.INFERNO_JUDGE, level: 1, loadout: [null, null, null], cap: 6, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.CRYSTAL_WEAVER]: { id: UnitType.CRYSTAL_WEAVER, level: 1, loadout: [null, null, null], cap: 6, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            // Tier 4
            [UnitType.TYRANT_REX]: { id: UnitType.TYRANT_REX, level: 1, loadout: [null, null, null, null], cap: 3, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.TEMPEST_LEVIATHAN]: { id: UnitType.TEMPEST_LEVIATHAN, level: 1, loadout: [null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.STAR_EATER]: { id: UnitType.STAR_EATER, level: 1, loadout: [null, null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.ETERNAL_GLACIER]: { id: UnitType.ETERNAL_GLACIER, level: 1, loadout: [null, null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.STORM_BRINGER]: { id: UnitType.STORM_BRINGER, level: 1, loadout: [null, null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.ABYSSAL_MAW]: { id: UnitType.ABYSSAL_MAW, level: 1, loadout: [null, null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.PESTILENCE_LORD]: { id: UnitType.PESTILENCE_LORD, level: 1, loadout: [null, null, null, null], cap: 2, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            // Human Units (Non-producing)
            [UnitType.HUMAN_MARINE]: { id: UnitType.HUMAN_MARINE, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_MILITIA]: { id: UnitType.HUMAN_MILITIA, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_K9_UNIT]: { id: UnitType.HUMAN_K9_UNIT, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_SCOUT]: { id: UnitType.HUMAN_SCOUT, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_MEDIC]: { id: UnitType.HUMAN_MEDIC, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_ENGINEER]: { id: UnitType.HUMAN_ENGINEER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_RIOT]: { id: UnitType.HUMAN_RIOT, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_RECON_DRONE]: { id: UnitType.HUMAN_RECON_DRONE, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            
            [UnitType.HUMAN_PYRO]: { id: UnitType.HUMAN_PYRO, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_GRENADIER]: { id: UnitType.HUMAN_GRENADIER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_SHOCK_TROOPER]: { id: UnitType.HUMAN_SHOCK_TROOPER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_SNIPER]: { id: UnitType.HUMAN_SNIPER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_CRYO_TROOPER]: { id: UnitType.HUMAN_CRYO_TROOPER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_CHEM_TROOPER]: { id: UnitType.HUMAN_CHEM_TROOPER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_ROCKET_TROOPER]: { id: UnitType.HUMAN_ROCKET_TROOPER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_GHOST]: { id: UnitType.HUMAN_GHOST, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            [UnitType.HUMAN_ASSAULT_BIKE]: { id: UnitType.HUMAN_ASSAULT_BIKE, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TECHNICAL]: { id: UnitType.HUMAN_TECHNICAL, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_APC]: { id: UnitType.HUMAN_APC, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_VULTURE]: { id: UnitType.HUMAN_VULTURE, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_FLAME_TANK]: { id: UnitType.HUMAN_FLAME_TANK, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TESLA_TANK]: { id: UnitType.HUMAN_TESLA_TANK, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            [UnitType.HUMAN_TANK]: { id: UnitType.HUMAN_TANK, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_SIEGE_TANK]: { id: UnitType.HUMAN_SIEGE_TANK, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_GOLIATH]: { id: UnitType.HUMAN_GOLIATH, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_RAILGUN_MECH]: { id: UnitType.HUMAN_RAILGUN_MECH, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TITAN_WALKER]: { id: UnitType.HUMAN_TITAN_WALKER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            [UnitType.HUMAN_HELICOPTER]: { id: UnitType.HUMAN_HELICOPTER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_FIGHTER_JET]: { id: UnitType.HUMAN_FIGHTER_JET, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_BOMBER]: { id: UnitType.HUMAN_BOMBER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_GUNSHIP]: { id: UnitType.HUMAN_GUNSHIP, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_BATTLECRUISER]: { id: UnitType.HUMAN_BATTLECRUISER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },

            [UnitType.HUMAN_BUNKER]: { id: UnitType.HUMAN_BUNKER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TURRET_MG]: { id: UnitType.HUMAN_TURRET_MG, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TURRET_CANNON]: { id: UnitType.HUMAN_TURRET_CANNON, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TURRET_MISSILE]: { id: UnitType.HUMAN_TURRET_MISSILE, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TURRET_LASER]: { id: UnitType.HUMAN_TURRET_LASER, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
            [UnitType.HUMAN_TESLA_COIL]: { id: UnitType.HUMAN_TESLA_COIL, level: 1, loadout: [], cap: 0, capLevel: 1, efficiencyLevel: 1, isProducing: false, productionProgress: 0 },
        },
        unitStockpile: {
            [UnitType.MELEE]: 0,
            [UnitType.RANGED]: 0,
            [UnitType.QUEEN]: 0,
            [UnitType.PYROVORE]: 0,
            [UnitType.CRYOLISK]: 0,
            [UnitType.OMEGALIS]: 0,
            [UnitType.ZERGLING_RAPTOR]: 0,
            [UnitType.EMBER_MITE]: 0,
            [UnitType.SPARK_FLY]: 0,
            [UnitType.FROST_WEEVIL]: 0,
            [UnitType.ACID_MAGGOT]: 0,
            [UnitType.LIGHTNING_SKINK]: 0,
            [UnitType.SPINE_HURLER]: 0,
            [UnitType.MAGMA_GOLEM]: 0,
            [UnitType.PLAGUE_BEARER]: 0,
            [UnitType.WINTER_WITCH]: 0,
            [UnitType.TYRANT_REX]: 0,
            [UnitType.TEMPEST_LEVIATHAN]: 0,
            [UnitType.BONE_BLADE]: 0,
            [UnitType.ACID_SPITTER]: 0,
            [UnitType.STATIC_ORB]: 0,
            [UnitType.CINDER_LING]: 0,
            [UnitType.FROST_SHARD]: 0,
            [UnitType.SIEGE_BEETLE]: 0,
            [UnitType.FROST_WARD]: 0,
            [UnitType.MAGMA_SPRAYER]: 0,
            [UnitType.SHOCK_ROACH]: 0,
            [UnitType.VILE_CRAWLER]: 0,
            [UnitType.PULSE_BEAST]: 0,
            [UnitType.CORRUPTOR]: 0,
            [UnitType.PHANTOM_ASSASSIN]: 0,
            [UnitType.INFERNO_JUDGE]: 0,
            [UnitType.CRYSTAL_WEAVER]: 0,
            [UnitType.STAR_EATER]: 0,
            [UnitType.ETERNAL_GLACIER]: 0,
            [UnitType.STORM_BRINGER]: 0,
            [UnitType.ABYSSAL_MAW]: 0,
            [UnitType.PESTILENCE_LORD]: 0,
            
            // Humans default 0
            [UnitType.HUMAN_MARINE]: 0,
            [UnitType.HUMAN_MILITIA]: 0,
            [UnitType.HUMAN_K9_UNIT]: 0,
            [UnitType.HUMAN_SCOUT]: 0,
            [UnitType.HUMAN_MEDIC]: 0,
            [UnitType.HUMAN_ENGINEER]: 0,
            [UnitType.HUMAN_RIOT]: 0,
            [UnitType.HUMAN_RECON_DRONE]: 0,
            [UnitType.HUMAN_PYRO]: 0,
            [UnitType.HUMAN_GRENADIER]: 0,
            [UnitType.HUMAN_SHOCK_TROOPER]: 0,
            [UnitType.HUMAN_SNIPER]: 0,
            [UnitType.HUMAN_CRYO_TROOPER]: 0,
            [UnitType.HUMAN_CHEM_TROOPER]: 0,
            [UnitType.HUMAN_ROCKET_TROOPER]: 0,
            [UnitType.HUMAN_GHOST]: 0,
            [UnitType.HUMAN_ASSAULT_BIKE]: 0,
            [UnitType.HUMAN_TECHNICAL]: 0,
            [UnitType.HUMAN_APC]: 0,
            [UnitType.HUMAN_VULTURE]: 0,
            [UnitType.HUMAN_FLAME_TANK]: 0,
            [UnitType.HUMAN_TESLA_TANK]: 0,
            [UnitType.HUMAN_TANK]: 0,
            [UnitType.HUMAN_SIEGE_TANK]: 0,
            [UnitType.HUMAN_GOLIATH]: 0,
            [UnitType.HUMAN_RAILGUN_MECH]: 0,
            [UnitType.HUMAN_TITAN_WALKER]: 0,
            [UnitType.HUMAN_HELICOPTER]: 0,
            [UnitType.HUMAN_FIGHTER_JET]: 0,
            [UnitType.HUMAN_BOMBER]: 0,
            [UnitType.HUMAN_GUNSHIP]: 0,
            [UnitType.HUMAN_BATTLECRUISER]: 0,
            [UnitType.HUMAN_BUNKER]: 0,
            [UnitType.HUMAN_TURRET_MG]: 0,
            [UnitType.HUMAN_TURRET_CANNON]: 0,
            [UnitType.HUMAN_TURRET_MISSILE]: 0,
            [UnitType.HUMAN_TURRET_LASER]: 0,
            [UnitType.HUMAN_TESLA_COIL]: 0,
        },
        production: {
            larvaCapBase: INITIAL_LARVA_CAP,
            queenIntervalLevel: 1,
            queenAmountLevel: 1,
            queenTimer: 0
        },
        metabolism: {
            villiCount: 0,
            taprootCount: 0,
            geyserCount: 0,
            breakerCount: 0,
            fermentingSacCount: 0,
            refluxPumpCount: 0,
            thermalCrackerCount: 0,
            fleshBoilerCount: 0,
            crackerHeat: 0,
            crackerOverheated: false,
            thoughtSpireCount: 0,
            hiveMindCount: 0,
            akashicRecorderCount: 0,
            spireAccumulator: 0,
            storageCount: 0,
            supplyCount: 0,
            necroSiphonCount: 0,
            redTideCount: 0,
            gaiaDigesterCount: 0,
            bloodFusionCount: 0,
            synapticResonatorCount: 0,
            entropyVentCount: 0,
            combatCortexCount: 0,
            geneArchiveCount: 0,
            omegaPointCount: 0
        },
        inventory: {
            consumables: {},
            plugins: []
        },
        globalBuffs: []
    },
    world: {
        currentRegionId: 0,
        regions: {
            1: { id: 1, isUnlocked: true, devourProgress: 0 }
        }
    },
    player: {
        lastSaveTime: Date.now(),
        prestigeLevel: 0,
        lifetimeDna: 0,
        mutationUpgrades: {
            metabolicSurge: 0,
            larvaFission: 0,
            geneticMemory: false
        },
        settings: {
            bgmVolume: 0.5,
            sfxVolume: 0.5
        }
    }
};
